//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 08:49:38 PM IST 
//


package com.dyasha.myjavaapp.jaxb.xsd2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dyasha.myjavaapp.jaxb.xsd2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dyasha.myjavaapp.jaxb.xsd2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CollegeInfo }
     * 
     */
    public CollegeInfo createCollegeInfo() {
        return new CollegeInfo();
    }

    /**
     * Create an instance of {@link CollegeInfo.StudentsData }
     * 
     */
    public CollegeInfo.StudentsData createCollegeInfoStudentsData() {
        return new CollegeInfo.StudentsData();
    }

    /**
     * Create an instance of {@link CollegeInfo.StudentsData.Students }
     * 
     */
    public CollegeInfo.StudentsData.Students createCollegeInfoStudentsDataStudents() {
        return new CollegeInfo.StudentsData.Students();
    }

}
